### ISSUE TITLE
can't npm install -S

### ISSUE THREAD

**Issue by dezmob** [ayushsharma82/ESP-DASH#35]
Hi there,

Just following the instructions to customize the frontend.

running `npm install -S` in the vue-frontend return me 

```
➜  vue-frontend git:(master) npm install -S

> fsevents@1.2.9 install /Users/me/ESP-DASH/vue-frontend/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download
[fsevents] Success: "/Users/me/ESP-DASH/vue-frontend/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> yorkie@2.0.0 install /Users/me/ESP-DASH/vue-frontend/node_modules/yorkie
> node bin/install.js

setting up Git hooks
can't find .git directory, skipping Git hooks installation

> node-sass@4.11.0 install /Users/me/ESP-DASH/vue-frontend/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/darwin-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/darwin-x64-72_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.11.0 postinstall /Users/me/ESP-DASH/vue-frontend/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/Cellar/node/12.4.0/bin/node /Users/me/ESP-DASH/vue-frontend/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/Cellar/node/12.4.0/bin/node',
gyp verb cli   '/Users/me/ESP-DASH/vue-frontend/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.4.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/local/bin/python2
gyp verb check python version `/usr/local/bin/python2 -c "import sys; print "2.7.16
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 12.4.0
gyp verb command install [ '12.4.0' ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: Cannot find module 'minipass'
gyp ERR! stack Require stack:
gyp ERR! stack - /Users/me/ESP-DASH/vue-frontend/node_modules/node-gyp/node_modules/tar/lib/pack.js
gyp ERR! stack - /Users/me/ESP-DASH/vue-frontend/node_modules/node-gyp/node_modules/tar/lib/create.js
gyp ERR! stack - /Users/me/ESP-DASH/vue-frontend/node_modules/node-gyp/node_modules/tar/index.js
gyp ERR! stack - /Users/me/ESP-DASH/vue-frontend/node_modules/node-gyp/lib/install.js
gyp ERR! stack - /Users/me/ESP-DASH/vue-frontend/node_modules/node-gyp/lib/node-gyp.js
gyp ERR! stack - /Users/me/ESP-DASH/vue-frontend/node_modules/node-gyp/bin/node-gyp.js
gyp ERR! stack     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:681:19)
gyp ERR! stack     at require (internal/modules/cjs/helpers.js:16:16)
gyp ERR! stack     at Object.<anonymous> (/Users/me/ESP-DASH/vue-frontend/node_modules/node-gyp/node_modules/tar/lib/pack.js:27:18)
gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:774:30)
gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:641:32)
gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:681:19)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/12.4.0/bin/node" "/Users/me/ESP-DASH/vue-frontend/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/me/ESP-DASH/vue-frontend/node_modules/node-sass
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
Build failed with error code: 7
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2019-06-20T15_12_33_123Z-debug.log
```

I'm on macOS Mojave

node installed with brew
node : v12.4.0
npm : 6.9.0

**Comment by ayushsharma82** [comment]
npm wasn't able to download a dependency. I don't know why that's occurring on your PC only. It might be a networking problem.

**Comment by dezmob** [comment]
well I just tried with yarn

```
➜  vue-frontend git:(master) npm install yarn -g
/usr/local/bin/yarn -> /usr/local/lib/node_modules/yarn/bin/yarn.js
/usr/local/bin/yarnpkg -> /usr/local/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.16.0
added 1 package in 1.213s

➜  vue-frontend git:(master) yarn
yarn install v1.16.0
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
warning @vue/cli-plugin-babel > webpack > micromatch > snapdragon > base > mixin-deep@1.3.1: Critical bug fixed in v2.0.1, please upgrade to the latest version.
warning @vue/cli-plugin-babel > webpack > micromatch > snapdragon > base > cache-base > set-value@2.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
warning @vue/cli-plugin-babel > webpack > micromatch > snapdragon > base > cache-base > union-value > set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
warning @vue/cli-plugin-eslint > eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > vue-apexcharts@1.4.0" has incorrect peer dependency "apexcharts@^3.6.6".
warning " > sass-loader@7.1.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
warning " > style-resources-loader@1.2.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 34.51s.

➜  vue-frontend git:(master) ✗ npm run serve

> esp-dash-webpage@1.4.0 serve /Users/me/ESP-DASH/vue-frontend
> vue-cli-service serve

 INFO  Starting development server...
 10% building 2/2 modules 0 active(node:20261) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
 98% after emitting unnamed compat pluginExecuting post-build scripts
Skipping Finalizing Vuejs Webpage in Development Mode


 DONE  Compiled successfully in 5393ms                                                          7:21:15 PM


  App running at:
  - Local:   http://localhost:8080/
  - Network: http://10.0.128.144:8080/

  Note that the development build is not optimized.
  To create a production build, run yarn build.
```

looks like it's just npm being npm

**Comment by Rotzbua** [comment]
> Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/darwin-x64-72_binding.node":

Simple answer:
no matching node-sass is available.
your node is to new for the release v4.11.0.
https://github.com/sass/node-sass/releases

**Comment by dezmob** [comment]
> > Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/darwin-x64-72_binding.node":
> 
> Simple answer:
> no matching node-sass is available.
> your node is to new for the release v4.11.0.
> https://github.com/sass/node-sass/releases

Yes that's it, with node-sass v4.12.0 I need to use node 11.

thanks you
